351 ThreadUpdateMutation
serlo/database-layer pull request #357
Opened 2023-01-05 11:03 UTC by AndreasHuber

2023-01-05 13:34 UTC, hugotiburtino requested changes

2023-01-05 13:34 UTC, hugotiburtino commented on server/src/thread/model.rs
> +                SELECT trashed FROM uuid WHERE id = ?
You can fetch this info in only one query, joining this query with the one in line 395.
use a join
``SELECT ...,, trashed FROM comment JOIN uuid ON uuid.id = comment.id ... `

2023-01-05 13:34 UTC, hugotiburtino commented on server/src/thread/model.rs
> +            Err(_) => {
We could map exactly the error (it should be sqlx:Error:RowNotFound and throw it accordingly. The others error should be a server error.

2023-01-05 13:34 UTC, hugotiburtino commented on server/src/thread/model.rs
> +        let is_trashed = match sqlx::query!(
Instead of using a `match` it is common to use `map_err` in this repo. 
I personally think it is easier to read with map_err

2023-01-05 13:35 UTC, hugotiburtino commented
thanks! Wonderful that you can already deliver a working code

2023-01-12 01:04 UTC, AndreasHuber commented
- Saving the edit date requires adding a column to the database table comment first, so this is missing or only the intent shown via commented code. 
- Touching the test cases for create comment / thread was not scope of the ticket but we had agreed I could do it here anyways.

2023-01-12 11:35 UTC, AndreasHuber commented
Question came up regarding naming convention. I thought EditCommentMutation would be a clear name but maybe the original suggestion ThreadUpdateMutation or something like ThreadEditCommentMutation is more consistent with existing naming. Please let me know and I can push an according rename. @kulla

2023-01-12 12:24 UTC, hugotiburtino approved these changes
@kulla @MoeHome we are applying the moto: merge first, ask later. 
If you have change request, please open a new issue.

2023-01-12 12:24 UTC, hugotiburtino commented on server/src/thread/messages.rs
> +    EditCommentMutation(edit_comment_mutation::Payload),
```suggestion
    ThreadEditMutation(edit_comment_mutation::Payload),
```

2023-01-12 12:24 UTC, hugotiburtino commented on server/src/thread/messages.rs
> +            ThreadMessage::EditCommentMutation(message) => {
```suggestion
            ThreadMessage::ThreadEditMutation(message) => {
```

2023-01-12 14:54 UTC, kulla commented
> @kulla @MoeHome we are applying the moto: merge first, ask later.

:+1:

>  I thought EditCommentMutation would be a clear name but maybe the original suggestion ThreadUpdateMutation or something like ThreadEditCommentMutation

In the current convention the first subject is somethink like a namespace. The namespace `thread` is perfect, so I would go with `ThreadEditCommentMutation`

2023-01-12 20:45 UTC, merged