Pin tools (Node.js, yarn cli, and Rust)
serlo/database-layer pull request #501
Opened 2023-07-10 16:04 UTC by eliflores

This PR adds the current versions used in the database-layer repository, the update of Rust will come separately. 

---
ℹ️  The update of the version of Rust will require additional changes. For example: an update of `sqlx-cli` that includes a deprecation of the `sqlx-data.json` file - ref: https://github.com/launchbadge/sqlx/commit/3f2ec6f91aa87db9f9f15adec1027b4126cde5f8). 
With the intention of making the changes more clear to follow and review, a separate PR will come with the upgrade of the Rust version 🦀

2023-07-10 20:15 UTC, AndreasHuber commented
For started sqlx upgrade see https://github.com/serlo/database-layer/tree/upgrade-sqlx-to-0.7.0. It needs some refactoring to compile again.

2023-07-10 20:17 UTC, AndreasHuber commented
Why would a Rust version upgrade require changes like sqlx? I think it shouldn't. 🤔

2023-07-10 20:21 UTC, AndreasHuber requested changes

2023-07-11 09:45 UTC, eliflores commented
Hi @AndreasHuber 
Thank you for the review!

> Why would a Rust version upgrade require changes like sqlx? I think it shouldn't. 🤔
After I changed the version of Rust to 1.70.0, I needed to re-install `sqlx-cli` and since I did not specify a version, the version ` v0.7.0` was installed (since it's the latest release), if I specify the version (i.e. `cargo install sqlx-cli --version 0.6.3`) then we don't need to upgrade =)

2023-07-11 09:46 UTC, eliflores commented on README.md
> +- [Rust](https://www.rust-lang.org) version from [.tool-versions](.tool-versions). [^1]
Oh, interesting. 
What would be your suggestion on what we could write on this line instead?

2023-07-11 10:28 UTC, AndreasHuber approved these changes

2023-07-11 10:41 UTC, merged